#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');
const DATA_DIR = path.join(ROOT, 'data');

console.log('Agentic EHR — Setup');
console.log('====================\n');

// 1. Create data directory
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  console.log('[OK] Created data/ directory');
} else {
  console.log('[OK] data/ directory exists');
}

// 2. Generate .env if missing
if (!fs.existsSync(ENV_FILE)) {
  const jwtSecret = crypto.randomBytes(64).toString('hex');
  const phiKey = crypto.randomBytes(32).toString('hex');

  const envContent = `# Agentic EHR Environment Configuration
# Generated by scripts/setup.js on ${new Date().toISOString()}

PORT=3000
NODE_ENV=development
AI_MODE=mock

# Authentication
JWT_SECRET=${jwtSecret}

# PHI Encryption (AES-256-GCM)
PHI_ENCRYPTION_KEY=${phiKey}

# Database
DATABASE_PATH=./data/ehr.db

# Claude API (optional — set AI_MODE=api to enable)
# ANTHROPIC_API_KEY=sk-ant-...

# Provider
PROVIDER_NAME=Dr. Provider
`;

  fs.writeFileSync(ENV_FILE, envContent);
  console.log('[OK] Generated .env with secure random keys');
  console.log('     JWT_SECRET: (generated)');
  console.log('     PHI_ENCRYPTION_KEY: (generated)');
} else {
  console.log('[OK] .env file exists');

  // Check for required keys
  const envContent = fs.readFileSync(ENV_FILE, 'utf8');
  const missing = [];
  if (!envContent.includes('JWT_SECRET=') || envContent.includes('JWT_SECRET=\n')) missing.push('JWT_SECRET');
  if (!envContent.includes('PHI_ENCRYPTION_KEY=') || envContent.includes('PHI_ENCRYPTION_KEY=\n')) missing.push('PHI_ENCRYPTION_KEY');

  if (missing.length > 0) {
    console.log(`[WARN] Missing keys in .env: ${missing.join(', ')}`);
    console.log('       Run this script with --regen-keys to generate them');
  }
}

// 3. Check Node version
const nodeVersion = parseInt(process.version.slice(1));
if (nodeVersion < 18) {
  console.log(`[WARN] Node.js ${process.version} detected. Node 18+ is required.`);
} else {
  console.log(`[OK] Node.js ${process.version}`);
}

// 4. Check for node_modules
if (!fs.existsSync(path.join(ROOT, 'node_modules'))) {
  console.log('[INFO] node_modules not found. Run: npm install');
} else {
  console.log('[OK] node_modules exists');
}

console.log('\nSetup complete. Run `npm run dev` to start the development server.');
